### PR TITLE
Update jerry-libc unreachable asserts

### PR DESCRIPTION
**Pull request by akosthekiss**
Newer compilers (especially clang) warn (and fail) on
`assert (!"message");` constructs typically used to assert on
unreachable code paths (multiple occurrences in jerry-libc). A more
up-to-date approach is to use `assert (false && "message");`. This
patch applies the pattern to all relevant asserts in jerry-libc.

JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akosthekiss** [comment]
JerryScript builds fine with clang-3.5 on x86-64/Ubuntu 14.04 with `CC=clang-3.5 tools/build.py --lto=off`. However, with `CC=clang-3.8` errors appear, e.g.:
```
jerryscript/jerry-libc/target/posix/jerry-libc-target.c:143:16: error: implicit conversion turns string literal into bool: 'char [17]' to 'bool'
      [-Werror,-Wstring-conversion]
      assert (!"unsupported mode");
```
This patch fixes these issues.
