### ISSUE TITLE
Conversion error to ‘ssize_t’ from ‘jerry_api_size_t’ (in main-unix.c, on arm/linux)

### ISSUE THREAD

**Issue by akiss77** [Samsung/jerryscript#942]
When cross-building jerry for arm/linux with 
`TOOLCHAIN=build/configs/toolchain_linux_armv7l-hf.cmake make NINJA=1 build.linux`, 
the following error is reported:

```
../../../main-unix.c: In function ‘main’:
../../../main-unix.c:563:7: error: conversion to ‘ssize_t’ from ‘jerry_api_size_t’ may change the sign of the result [-Werror=sign-conversion]
       ssize_t sz = jerry_api_string_to_char_buffer (err_str_p, err_str_buf, err_str_size);
```

**Comment by akiss77** [comment]
Introduced by a187e6d6

**Comment by akiss77** [comment]
Solved by #943
